name: Deploy & Run Databricks Job (Test)

on:
  push:
    branches: ["main"]

jobs:
  deploy_and_run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Ensure Cluster Ready
        run: |
          export DATABRICKS_HOST="https://adb-3960540793376249.9.azuredatabricks.net"
          export DATABRICKS_TOKEN="dapifffd4cf7e7f4dd37b2a317d48d41d132-3"

          databricks clusters wait 1124-094650-0nervcma

      - name: Create Job in Databricks
        run: |
          export DATABRICKS_HOST="https://adb-3960540793376249.9.azuredatabricks.net"
          export DATABRICKS_TOKEN="dapifffd4cf7e7f4dd37b2a317d48d41d132-3"

          JOB_ID=$(databricks jobs create --json-file end_to_end.json | jq -r '.job_id')
          echo "Created Job ID: $JOB_ID"
          echo "JOB_ID=$JOB_ID" >> $GITHUB_ENV

      - name: Trigger Job Run
        run: |
          export DATABRICKS_HOST="https://adb-3960540793376249.9.azuredatabricks.net"
          export DATABRICKS_TOKEN="dapifffd4cf7e7f4dd37b2a317d48d41d132-3"

          databricks jobs run "$JOB_ID"
