name: CI
 
on:
  #push:
    #branches: [ "main" ]  # make sure both have to be uncommented
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
 
    - name: Setup Databricks CLI (official)
      uses: databricks/setup-cli@main
 
    - name: Deploy repo to Azure Databricks Workspace
      run: |
        export DATABRICKS_HOST="https://adb-1670050298591902.2.azuredatabricks.net"
        export DATABRICKS_TOKEN="dapica208467099d1366845363dafb32d8aa-3"
        databricks workspace import-dir . \
        /Workspace/Users/deni.lakamsani@snp.com/GitDeployment \
        --overwrite

       
